
# This is a basic workflow to help you get started with the Run Jtest action.
name: Jtest with Maven

on:
  # Trigger the workflow on push or pull request events but only for the main branch.
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel.
jobs:
  build:
    name: Analyze project with Jtest
    
    permissions:
      # required for all workflows
      security-events: write
      actions: read           # 推荐：用于访问工作流信息
      contents: read          # 推荐：用于读取仓库内容
    
    # Specifies the type of runner that the job will run on.
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job.
    steps:
    
    # Checks out your repository under $GITHUB_WORKSPACE, so that your job can access it.
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.JTESTRUNNER }}
        fetch-depth: 0
    
    # Generates the jtest.data.json input file.
    - name: Run Jtest Unit Testing
      run: mvn clean test-compile jtest:agent test jtest:jtest -D'jtest.config="builtin://Unit Tests" -J-Duser.language=en -J-Duser.country=US' 

    # Runs code analysis with Jtest
    # - name: Run Jtest
    #   id: jtest
    #   uses: parasoft/run-jtest-action@2.0.2
    #   with:
    #     #Uses the jtest.data.json generated with the Maven command in the previous step
    #     installDir: 'D:/Softwares/Parasoft/parasoft_jtest_2025.2.0_win32_x86_64/jtest'
    #     input: target/jtest/jtest.data.json
    #     additionalParams: '-J-Duser.language=en -J-Duser.country=US'

    # Uploads analysis results in the SARIF format, so that they are displayed as GitHub code scanning alerts.
    # - name: Upload results (SARIF)
    #   if: always()
    #   uses: github/codeql-action/upload-sarif@v4
    #   with:
    #     sarif_file: reports/report.sarif # reports is a default location for reports directory

    # - name: Deploy Reports to GitHub Pages
    #   uses: peaceiris/actions-gh-pages@v3
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     publish_dir: ./reports
    #     destination_dir: reports
    #     keep_files: true

    # Uploads an archive that includes all report files (.xml, .html, .sarif).
    - name: Archive reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: Unit Testing reports
        path: reports/*.*


